version: 2.1

npm_cache_key: &npm_cache_key v1-dependencies-{{ checksum "package-lock.json" }}
sketch_ib_cache_key: &sketch_ib_cache_key sketch-lib-{{ .Branch }}

use_node_image: &use_node_image
  docker:
    - image: circleci/node:12.13.0

use_cypress_image: &use_cypress_image
  docker:
    - image: cypress/base:12.13.0

dist_folder: &dist_folder dist

executors:
  node_executor:
    <<: *use_node_image

commands:
  lint:
    description: "Lint"
    parameters:
      package:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: *npm_cache_key
      - restore_cache:
          key: *sketch_ib_cache_key
      - run: ls -l ./dist/sketch-lib/** || echo "dist folder not present"
      - run: npm run lint -- "<< parameters.package >>" ||
          (echo "Lint errors detected. Please run ''npm run lint -- --fix''" ; exit 1)

  test:
    description: "Test"
    parameters:
      package:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: *npm_cache_key
      - restore_cache:
          key: *sketch_ib_cache_key
      - run: ls -l ./dist/sketch-lib/** || echo "dist folder not present"
      - run: npm run test.ci -- --passWithNoTests --reporters=default --reporters=jest-junit --maxWorkers=2 -- "projects/<< parameters.package >>"
      - run: ls -l ./dist/sketch-lib/** || echo "dist folder not present"

  build-package:
    description: "Build Package"
    parameters:
      package:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: *npm_cache_key
      - run: ls -l ./dist/sketch-lib/** || echo "dist folder not present"
      - run: npm run ng -- build << parameters.package >>
# jobs:
#   install:
#     executor: node_executor
#     steps:
#       - checkout
#       - restore_cache:
#           key: *npm_cache_key
#       - run: npm ci
#       - save_cache:
#           key: *npm_cache_key
#           paths:
#             - node_modules

#   # Lint
#   lint-sketch-lib:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "sketch-lib"

#   lint-sketch-ingestor:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "sketch-ingestor"

#   lint-css-codegen:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "css-codegen"

#   lint-svg-codegen:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "svg-codegen"

#   lint-xaml-codegen:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "xaml-codegen"

#   lint-web-codegen:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "web-codegen"

#   lint-web-component-codegen:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "web-component-codegen"

#   lint-angular-codegen:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "angular-codegen"

#   lint-vue-codegen:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "vue-codegen"

#   lint-lit-element-codegen:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "lit-element-codegen"

#   lint-react-codegen:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "react-codegen"

#   lint-stencil-codegen:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "stencil-codegen"

#   lint-app:
#     executor: node_executor
#     steps:
#       - lint:
#           package: "xlayers"

#   # Tests
#   test-sketch-ingestor:
#     executor: node_executor
#     steps:
#       - test:
#           package: "sketch-ingestor"

#   test-sketch-lib:
#     executor: node_executor
#     steps:
#       - test:
#           package: "sketch-lib"

#   test-css-codegen:
#     executor: node_executor
#     steps:
#       - test:
#           package: "css-codegen"

#   test-svg-codegen:
#     executor: node_executor
#     steps:
#       - test:
#           package: "svg-codegen"

#   test-xaml-codegen:
#     executor: node_executor
#     steps:
#       - test:
#           package: "xaml-codegen"

#   test-web-codegen:
#     executor: node_executor
#     steps:
#       - test:
#           package: "web-codegen"

#   test-web-component-codegen:
#     executor: node_executor
#     steps:
#       - test:
#           package: "web-component-codegen"

#   test-angular-codegen:
#     executor: node_executor
#     steps:
#       - test:
#           package: "angular-codegen"

#   test-vue-codegen:
#     executor: node_executor
#     steps:
#       - test:
#           package: "vue-codegen"

#   test-lit-element-codegen:
#     executor: node_executor
#     steps:
#       - test:
#           package: "lit-element-codegen"

#   test-react-codegen:
#     executor: node_executor
#     steps:
#       - test:
#           package: "react-codegen"

#   test-stencil-codegen:
#     executor: node_executor
#     steps:
#       - test:
#           package: "stencil-codegen"

#   test-app:
#     executor: node_executor
#     steps:
#       - test:
#           package: "src/app/"

#   # Build package
#   build-sketch-lib:
#     executor: node_executor
#     steps:
#       - build-package:
#           package: "sketch-lib"
#       - save_cache:
#           key: *sketch_ib_cache_key
#           paths:
#             - dist/sketch-lib

#   build-sketch-ingestor:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "sketch-ingestor"

#   build-css-codegen:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "css-codegen"

#   build-svg-codegen:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "svg-codegen"

#   build-xaml-codegen:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "xaml-codegen"

#   build-web-codegen:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "web-codegen"

#   build-web-component-codegen:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "web-component-codegen"

#   build-angular-codegen:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "angular-codegen"

#   build-vue-codegen:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "vue-codegen"

#   build-lit-element-codegen:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "lit-element-codegen"

#   build-react-codegen:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "react-codegen"

#   build-stencil-codegen:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "stencil-codegen"

#   build-app:
#     executor: node_executor
#     steps:
#       - restore_cache:
#           key: *sketch_ib_cache_key
#       - build-package:
#           package: "xlayers"

#   # Test E2E
#   test-e2e:
#     <<: *use_cypress_image
#     steps:
#       - checkout
#       - run: npm ci
#       - restore_cache:
#           key: *npm_cache_key
#       - attach_workspace:
#           at: *dist_folder
#       - run: npm run e2e

# workflows:
#   version: 2
#   # "Lint All":
#   #   jobs:
#   #     ###################
#   #     - install
#   #     - lint-app:
#   #         requires:
#   #           - install
#   #     - lint-sketch-ingestor:
#   #         requires:
#   #           - install
#   #     - lint-css-codegen:
#   #         requires:
#   #           - install
#   #     - lint-svg-codegen:
#   #         requires:
#   #           - install
#   #     - lint-xaml-codegen:
#   #         requires:
#   #           - install
#   #     - lint-web-codegen:
#   #         requires:
#   #           - install
#   #     - lint-web-component-codegen:
#   #         requires:
#   #           - install
#   #     - lint-angular-codegen:
#   #         requires:
#   #           - install
#   #     - lint-vue-codegen:
#   #         requires:
#   #           - install
#   #     - lint-stencil-codegen:
#   #         requires:
#   #           - install
#   #     - lint-lit-element-codegen:
#   #         requires:
#   #           - install
#   #     - lint-react-codegen:
#   #         requires:
#   #           - install

#   # "E2E Testing":
#   #   jobs:
#   #     - install
#   #     - test-e2e:
#   #         requires:
#   #           - install

#   "Test and Build":
#     jobs:
#       - install

#       ###################
#       # Test & Build core libs
#       - build-sketch-lib:
#           requires:
#             - install
#       - test-sketch-lib:
#           requires:
#             - build-sketch-lib

#       ###################
#       # Test & Build other libs
#       - build-sketch-ingestor:
#           requires:
#             - build-sketch-lib
#       - build-css-codegen:
#           requires:
#             - build-sketch-lib
#       - build-svg-codegen:
#           requires:
#             - build-sketch-lib
#       - build-xaml-codegen:
#           requires:
#             - build-css-codegen
#             - build-svg-codegen
#             - build-sketch-lib
#       - build-web-codegen:
#           requires:
#             - build-css-codegen
#             - build-svg-codegen
#             - build-sketch-lib
#       - build-web-component-codegen:
#           requires:
#             - build-web-codegen
#             - build-sketch-lib
#       - build-angular-codegen:
#           requires:
#             - build-web-codegen
#             - build-sketch-lib
#       - build-vue-codegen:
#           requires:
#             - build-web-codegen
#             - build-sketch-lib
#       - build-stencil-codegen:
#           requires:
#             - build-web-codegen
#             - build-sketch-lib
#       - build-lit-element-codegen:
#           requires:
#             - build-web-codegen
#             - build-sketch-lib
#       - build-react-codegen:
#           requires:
#             - build-web-codegen
#             - build-sketch-lib

#       ###################
#       - test-sketch-ingestor:
#           requires:
#             - build-sketch-ingestor
#       - test-css-codegen:
#           requires:
#             - build-css-codegen
#       - test-svg-codegen:
#           requires:
#             - build-svg-codegen
#       - test-xaml-codegen:
#           requires:
#             - build-xaml-codegen
#       - test-web-codegen:
#           requires:
#             - build-web-codegen
#       - test-web-component-codegen:
#           requires:
#             - build-web-component-codegen
#       - test-angular-codegen:
#           requires:
#             - build-angular-codegen
#       - test-vue-codegen:
#           requires:
#             - build-vue-codegen
#       - test-stencil-codegen:
#           requires:
#             - build-stencil-codegen
#       - test-lit-element-codegen:
#           requires:
#             - build-lit-element-codegen
#       - test-react-codegen:
#           requires:
#             - build-react-codegen

#       ###################
#       - build-app:
#           requires:
#             - build-sketch-lib
#             - build-sketch-ingestor
#             - build-css-codegen
#             - build-svg-codegen
#             - build-xaml-codegen
#             - build-web-codegen
#             - build-web-component-codegen
#             - build-angular-codegen
#             - build-vue-codegen
#             - build-stencil-codegen
#             - build-lit-element-codegen
#             - build-react-codegen

#       - test-app:
#           requires:
#             - build-app
